version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  dbm-test2: dbm/dbm-test2@0.0.3
# Orchestrate or schedule a set of jobs
jobs:
  dbm-test: 
          docker:
            - image: cimg/openjdk:16.0.2
          steps:
            - checkout
            - dbm-test2/download-automation-jar
            - dbm-test2/validate:
                project_name: "CircleTest1"
                environment_name: "Release Source"
                package_name: "V0"
                server_address: "35.239.85.41:7017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"
                password: $DBM_PASSWORD
            - dbm-test2/create-manifest-file:
                path_to_scripts_folder: "V3"
            - run: zip -r V3.zip V3/*
            - dbm-test2/build:
                project_name: "MSSQL1"
                environment_name: "Dev_Env_1"
                server_address: "35.239.85.41:7017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"
            - dbm-test2/upgrade:
                project_name: "MSSQL1"
                environment_name: "Release Source"
                package_name: "V1"
                server_address: "35.239.85.41:7017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"

workflows:
  test-run:
    jobs:
      - dbm-test
