version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  dbm-test2: dbm/dbm-test2@0.0.2
# Orchestrate or schedule a set of jobs
jobs:
  dbm-test: 
          docker:
            - image: cimg/openjdk:16.0.2
          steps:
            - checkout
            - dbm-test2/download-automation-jar
            - dbm-test2/validate:
                environment_name: "Release Source"

workflows:
  test-run:
    jobs:
      - dbm-test
