version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  dbm-test2: dbm/dbm-test2@0.0.6
# Orchestrate or schedule a set of jobs
jobs:
  dbm-test: 
          docker:
            - image: cimg/openjdk:16.0.2
          steps:
            - checkout
            - dbm-test2/download-automation-jar
            - dbm-test2/import-project:
                file_path: "project.json"
                server_address: "35.239.85.41:7017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"            
            - dbm-test2/create-manifest-file:
                path_to_scripts_folder: "V3"
            - run: cd V3&&zip -r ../V3.zip *&&cd ..
            - dbm-test2/package:
                project_name: "DEMO"
                file_path: "V3.zip"
                server_address: "35.239.85.41:7017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"
            - dbm-test2/pre-check:
                project_name: "DEMO"
                package_name: "V3"
                server_address: "35.239.85.41:7017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"
            - dbm-test2/upgrade:
                project_name: "DEMO"
                environment_name: "Release Source"
                package_name: "V3"
                server_address: "35.239.85.41:7017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"                            
            - dbm-test2/build:
                project_name: "DEMO"
                environment_name: "Dev_Env_1"
                package_name: "V4"
                server_address: "35.239.85.41:7017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"
            - dbm-test2/upgrade:
                project_name: "DEMO"
                environment_name: "Release Source"
                package_name: "V4"
                server_address: "35.239.85.41:7017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"                             


workflows:
  test-run:
    jobs:
      - dbm-test
